/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CarStatus = IDL.Variant({
  'idle' : IDL.Null,
  'driving' : IDL.Null,
  'parked' : IDL.Null,
});
export const Time = IDL.Int;
export const CarProfile = IDL.Record({
  'status' : CarStatus,
  'model' : IDL.Text,
  'nickname' : IDL.Text,
  'batteryLevel' : IDL.Nat,
  'owner' : IDL.Principal,
  'lastUpdated' : Time,
});
export const BatteryAlert = IDL.Record({
  'car' : CarProfile,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Message = IDL.Record({
  'to' : IDL.Opt(IDL.Principal),
  'content' : IDL.Text,
  'from' : IDL.Principal,
  'read' : IDL.Bool,
  'timestamp' : Time,
});
export const RegisterCarInput = IDL.Record({
  'model' : IDL.Text,
  'nickname' : IDL.Text,
  'batteryLevel' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCarProfile' : IDL.Func([], [], []),
  'getAlertFeed' : IDL.Func([], [IDL.Vec(BatteryAlert)], ['query']),
  'getAllActiveCars' : IDL.Func([], [IDL.Vec(CarProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getOwnCarProfile' : IDL.Func([], [CarProfile], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markMessagesAsRead' : IDL.Func([], [], []),
  'registerCar' : IDL.Func([RegisterCarInput], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Opt(IDL.Principal), IDL.Text], [], []),
  'updateBatteryLevel' : IDL.Func([IDL.Nat], [], []),
  'updateStatus' : IDL.Func([CarStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CarStatus = IDL.Variant({
    'idle' : IDL.Null,
    'driving' : IDL.Null,
    'parked' : IDL.Null,
  });
  const Time = IDL.Int;
  const CarProfile = IDL.Record({
    'status' : CarStatus,
    'model' : IDL.Text,
    'nickname' : IDL.Text,
    'batteryLevel' : IDL.Nat,
    'owner' : IDL.Principal,
    'lastUpdated' : Time,
  });
  const BatteryAlert = IDL.Record({ 'car' : CarProfile, 'timestamp' : Time });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Message = IDL.Record({
    'to' : IDL.Opt(IDL.Principal),
    'content' : IDL.Text,
    'from' : IDL.Principal,
    'read' : IDL.Bool,
    'timestamp' : Time,
  });
  const RegisterCarInput = IDL.Record({
    'model' : IDL.Text,
    'nickname' : IDL.Text,
    'batteryLevel' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCarProfile' : IDL.Func([], [], []),
    'getAlertFeed' : IDL.Func([], [IDL.Vec(BatteryAlert)], ['query']),
    'getAllActiveCars' : IDL.Func([], [IDL.Vec(CarProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getOwnCarProfile' : IDL.Func([], [CarProfile], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markMessagesAsRead' : IDL.Func([], [], []),
    'registerCar' : IDL.Func([RegisterCarInput], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Opt(IDL.Principal), IDL.Text], [], []),
    'updateBatteryLevel' : IDL.Func([IDL.Nat], [], []),
    'updateStatus' : IDL.Func([CarStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };