/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BatteryAlert { 'car' : CarProfile, 'timestamp' : Time }
export interface CarProfile {
  'status' : CarStatus,
  'model' : string,
  'nickname' : string,
  'batteryLevel' : bigint,
  'owner' : Principal,
  'lastUpdated' : Time,
}
export type CarStatus = { 'idle' : null } |
  { 'driving' : null } |
  { 'parked' : null };
export interface Message {
  'to' : [] | [Principal],
  'content' : string,
  'from' : Principal,
  'read' : boolean,
  'timestamp' : Time,
}
export interface RegisterCarInput {
  'model' : string,
  'nickname' : string,
  'batteryLevel' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCarProfile' : ActorMethod<[], undefined>,
  'getAlertFeed' : ActorMethod<[], Array<BatteryAlert>>,
  'getAllActiveCars' : ActorMethod<[], Array<CarProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMessages' : ActorMethod<[], Array<Message>>,
  'getOwnCarProfile' : ActorMethod<[], CarProfile>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markMessagesAsRead' : ActorMethod<[], undefined>,
  'registerCar' : ActorMethod<[RegisterCarInput], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[[] | [Principal], string], undefined>,
  'updateBatteryLevel' : ActorMethod<[bigint], undefined>,
  'updateStatus' : ActorMethod<[CarStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];